- name: Set etcd facts needed for generating certs
  hosts:
    - masters
    - nodes
  roles:
  - openshift_facts
  tasks:
  - openshift_facts:
      role: "{{ item.role }}"
      local_facts: "{{ item.local_facts }}"
    with_items:
      - role: common
        local_facts:
          deployment_type: "{{ openshift_deployment_type }}"

- name: Configure docker for containerized installs
  hosts:
    - masters
    - nodes
  handlers:
    - name: restart docker
      service: name=docker state=restarted
  tasks:
    - stat: path=/etc/sysconfig/docker
      register: docker_check
    - set_fact:
        docker_additional_registries: "{{ lookup('oo_option', 'docker_additional_registries')
                                        | oo_split() | union(['registry.access.redhat.com'])
                                        |  difference(['']) }}"
      when: openshift.common.deployment_type == 'enterprise'
    - set_fact:
        docker_additional_registries: "{{ lookup('oo_option', 'docker_additional_registries')
                                      | oo_split() | difference(['']) }}"
      when: openshift.common.deployment_type != 'enterprise'
    - name: Add personal registries
      lineinfile:
        dest: /etc/sysconfig/docker
        regexp: '^ADD_REGISTRY=.*$'
        line: "ADD_REGISTRY='{{ docker_additional_registries
                            | oo_prepend_strings_in_list('--add-registry ') | join(' ') }}'"
      when: docker_check.stat.isreg and docker_additional_registries
      notify:
        - restart docker

    - name: Block registries
      lineinfile:
        dest: /etc/sysconfig/docker
        regexp: '^BLOCK_REGISTRY=.*$'
        line: "BLOCK_REGISTRY='{{ lookup('oo_option', 'docker_blocked_registries') | oo_split()
                              | oo_prepend_strings_in_list('--block-registry ') | join(' ') }}'"
      when: docker_check.stat.isreg and
          lookup('oo_option', 'docker_blocked_registries') != ''
      notify:
        - restart docker

    - name: Grant access to additional insecure registries
      lineinfile:
        dest: /etc/sysconfig/docker
        regexp: '^INSECURE_REGISTRY=.*'
        line: "INSECURE_REGISTRY='{{ lookup('oo_option', 'docker_insecure_registries') | oo_split()
                              | oo_prepend_strings_in_list('--insecure-registry ') | join(' ') }}'"
      when: docker_check.stat.isreg and
          lookup('oo_option', 'docker_insecure_registries') != ''
      notify:
        - restart docker
