---
openshift_cert_dir: /etc/openshift/node
openshift_master_ca_dir: /etc/openshift/master
openshift_master_ca_cert: "{{ openshift_master_ca_dir }}/ca.crt"
openshift_master_ca_key: "{{ openshift_master_ca_dir }}/ca.key"
