---
# tasks file for docker
- name: Install docker
  yum:
    pkg: docker
  when: not openshift.common.is_atomic | bool

- name: enable and start the docker service
  service:
    name: docker
    enabled: yes
    state: started
  register: start_result

- set_fact:
    docker_service_status_changed = start_result | changed

